import fs from 'node:fs'
const names = ['organizer', 'recorder', 'mirror']
fs.writeFileSync('lib/agents/prompts.mjs', '// Generated by npm run prompts.\n' + names.map(n =>
  `export const ${n}Prompt = ${JSON.stringify(fs.readFileSync(`lib/agents/prompts/${n}.md`, 'utf8'))}\n`).join(''))
